### ISSUE TITLE
is there a way to add 2 playlist players in one page ?

### ISSUE THREAD

**Issue by izzuco** [carloscabo/responsive-youtube-player-with-playlist#3]
I have a scenario where i need to add 2 players is there a way ,I have tried adding 2 js files and CSS files where i seperated the naming like RYPP and RYPP1 ,same with the container classes but still one is loading and other is not

**Comment by carloscabo** [comment]
Not. At this moment that is not possible. Let me think about it a couple of days, maybe it's easier than I think.

**Comment by izzuco** [comment]
Nice :) Hope there is a easy way out ,i feel there is an issue with dom element selection ,thanks for the reply

**Comment by carloscabo** [comment]
I've just uploaded a new version with support for several RYPP instances in the same page. Take a look to the `demo.html` file. Several changes were needed in order to be able to configure each player with it's own options. Hope now fits your needs. If you find any bug please let me know.
Remember you need to create your own **Youtub API Key** ;)
