### ISSUE TITLE
Removing Ads

### ISSUE THREAD

**Issue by inglesuniversal** [carloscabo/responsive-youtube-player-with-playlist#7]
Any update Carlos if you have discovered how to safely remove ads from your YouTube Player?

Also... I am working on a script to load lyrics for a YouTube music Video... Is there a way I can use your script to get ONLY this from the Video META data:

Artist

Track

So I can transfer those VALUES into PHP and find the lyrics online.

Thanks!

**Comment by carloscabo** [comment]
Hi.
As far as I know there is NOT a way to remove YouTube Ads as they are inside the <iframe> that YT API creates, so I think it's not possible to do that (and if there is a workaround I'm pretty sure is against the YT policies).

For the second subject.
You have an Youtube API in PHP... https://developers.google.com/youtube/v3/code_samples/php?hl=es I think would be easier to get the videos directly in PHP instead of passing information from JS to PHP... (maybe I did not understood what you want to do exactly ;)
